apiVersion: v1
kind: Service
metadata:
  name: ${MASTER_NAME}
  namespace: ${NAMESPACE}
  labels:
    app: spark
    component: master
    user: ${USERNAME}
    cluster-id: ${CLUSTER_ID}
spec:
  ports:
    - port: ${MASTER_PORT}
      targetPort: ${MASTER_PORT}
      name: spark
    - port: ${MASTER_WEBUI_PORT}
      targetPort: ${MASTER_WEBUI_PORT}
      name: webui
  selector:
    app: spark
    component: master
    user: ${USERNAME}
    cluster-id: ${CLUSTER_ID}