apiVersion: v1
kind: Service
metadata:
  name: {{ MASTER_NAME }}
  namespace: {{ NAMESPACE }}
  labels:
    app: spark
    component: master
    user: {{ USERNAME }}
    cluster-id: {{ CLUSTER_ID }}
spec:
  ports:
    - port: {{ SPARK_MASTER_PORT|int }}
      targetPort: {{ SPARK_MASTER_PORT|int }}
      name: spark
    - port: {{ SPARK_MASTER_WEBUI_PORT|int }}
      targetPort: {{ SPARK_MASTER_WEBUI_PORT|int }}
      name: webui
      #TODO REMOVE THIS IN FAVOR OF JUPYTER SERVICE PROXY
    - port: 80
      targetPort: {{ MASTER_WEBUI_PORT|int }}
      name: proxyui
  selector:
    app: spark
    component: master
    user: {{ USERNAME }}
    cluster-id: {{ CLUSTER_ID }}