apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ MASTER_NAME }}
  namespace: {{ NAMESPACE }}
  labels:
    app: spark
    component: master
    user: {{ USERNAME }}
    cluster-id: {{ CLUSTER_ID }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark
      component: master
      user: {{ USERNAME }}
      cluster-id: {{ CLUSTER_ID }}
  template:
    metadata:
      labels:
        app: spark
        component: master
        user: {{ USERNAME }}
        cluster-id: {{ CLUSTER_ID }}
    spec:
      enableServiceLinks: False
      hostname: spark-master-{{ USERNAME_LOWER }}
      {% if MASTER_NODE_SELECTOR_VALUES and MASTER_NODE_SELECTOR_VALUES.strip() %}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      {% for node in MASTER_NODE_SELECTOR_VALUES.split(',') if node.strip() %}
                      - {{ node.strip() }}
                      {% endfor %}
      {% endif %}
      containers:
        - name: spark-master
          image: {{ IMAGE }}
          imagePullPolicy: {{ IMAGE_PULL_POLICY }}
          ports:
            - containerPort: {{ SPARK_MASTER_PORT }}
              name: master-comm
              protocol: TCP
            - containerPort: {{ SPARK_MASTER_WEBUI_PORT }}
              name: master-ui
              protocol: TCP
          env:
            - name: SPARK_MODE
              value: master
            - name: SPARK_MASTER_PORT
              value: {{ SPARK_MASTER_PORT }}
            - name: SPARK_MASTER_WEBUI_PORT
              value: {{ SPARK_MASTER_WEBUI_PORT }}
            - name: SPARK_MASTER_HOST
              value: spark-master-{{ USERNAME_LOWER }}


# These should match SPARK_MASTER_CORES and SPARK_MASTER_MEMORY, and also be set as env vars, to let spark itself
# Know how much resources it has available.

#          resources:
#            requests:
#              memory: "{{ MASTER_MEMORY }}"
#              cpu: "{{ MASTER_CORES }}"
#            limits:
#              memory: "{{ MASTER_MEMORY }}"
#              cpu: "{{ MASTER_CORES }}"