# This Kubernetes service file is intended for local environment deployment only.
apiVersion: v1
kind: Service
metadata:
  name: cdm-spark-cluster-manager-api
  namespace: cdm-jupyterhub
  labels:
    app: cdm-spark-cluster-manager-api
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      name: http
  selector:
    app: cdm-spark-cluster-manager-api